force-app/main/default/objects/Case/fields/Opportunity_Case__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Case</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Number_Of_Case__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Case__c</fullName>
    <label>Number Of Case</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OpportunityCaseBatch.cls
global class OpportunityCaseBatch implements Database.Batchable <SObject> {
    //START METHOD
    global Database.QueryLocator start(Database.BatchableContext bc){
        String Query='select id,Name,createdDate,Number_Of_Case__c,(select id from cases__r) from Opportunity order by createdDate DESC Limit 1';
        //Integer size = cases__r.size();
        return Database.getQueryLocator(Query);
    }
    //EXECUTE METHOD
    global void execute(Database.BatchableContext bc, List<Opportunity> scopeList){
        System.debug('scope : ' + scopeList);
        Integer count = 0;
        Id oppIds;
        List<Case> CaseList = new List <Case>();
			
        List <Case> delcaseLst = new List <Case>();
		for(Opportunity opp : scopeList){
			count = opp.cases__r.size();
            system.debug('###'+count);
			
			
			Integer num;
			if(count < 5){
				for(num = count; num < 5 ; num++){
					Case caseObj = new Case();
					caseObj.Status = 'New';
					caseObj.Origin = 'Web';
					caseObj.Opportunity_Case__c = opp.Id;
					CaseList.add(caseObj);
				}
			}else{
				for(num = 5; num < count  ; num++){
					delcaseLst.add(opp.cases__r[num]); 
				}
			}
		}
		if(!CaseList.isEmpty()){
			insert CaseList;
            system.debug('###'+CaseList);
		}
		if(!delcaseLst.isEmpty()){
			delete delcaseLst;
            system.debug('###'+delcaseLst);
		}
		
    }
	//FINISH METHOD
	global void finish(Database.BatchableContext bc){
		
	}
}