force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <label>Events</label>
    <nameField>
        <label>Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Choice__c.field-meta.xml
<CustomField>
    <fullName>Choice__c</fullName>
    <inlineHelpText>Enter value with comma separated</inlineHelpText>
    <label>Choice</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Events__c.field-meta.xml
<CustomField>
    <fullName>Events__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Events</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Question</relationshipLabel>
    <relationshipName>Question</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EventRecordCtrl.cls
public class EventRecordCtrl {
    @AuraEnabled//Method to get the List of event List
    public static List<DataWrapper> getAllEvent(){
        List<DataWrapper> DataWrapperList=new List<DataWrapper>();      
        List<Events__c> eventList = [Select Id,Name from Events__c];
        if(!eventList.isEmpty()){
            for(Events__c eventObj : eventList){
                DataWrapper dataWrapperObj=new DataWrapper();
                dataWrapperObj.label=eventObj.name;
                dataWrapperObj.value=eventObj.name;
                dataWrapperObj.eventId=eventObj.ID;
                DataWrapperList.add(dataWrapperObj);
            }
            
        }
        system.debug('@#@# '+eventList);
        System.debug('@@@@'+DataWrapperList);
        return DataWrapperList;
    }
    
    public Class DataWrapper{
        @auraEnabled
        public String label;
        @auraEnabled
        public String value;
        @auraEnabled
        public String eventId;
        
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Question__c> getQuesData(String evtId) {
        System.debug('evtId '+evtId);      
        List <Question__c> quesLst = [select id,Name,Type__c,Events__c,Choice__c from Question__c where Events__c =:evtId];
        system.debug('quesLst '+quesLst);
        return quesLst;
    }
}