force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/student__c/student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/student__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <label>Fee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Defaulter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StudentDefaulter_Test.cls
@isTest
public class StudentDefaulter_Test {
@TestSetup
    public static void testSetup(){
        
    }
    @istest
    public static void testSetupMtd(){
        
        List <student__c> studentList = new List <student__c> ();
        class__c cls = new class__c (Name__c='10th');
        insert cls;
        
        student__c stu = new student__c (Last_Name__c='ABCD',Class__c=cls.id,Fee__c='Defaulter');
        insert stu;
        
        student__c stu1 = new student__c (Last_Name__c='ABCD',Class__c=cls.id,Fee__c='Defaulter');
        insert stu1;
        
    }
}