force-app/main/default/objects/Claim_settlement__c/Claim_settlement__c.object-meta.xml
<CustomObject>
    <label>Claim settlement</label>
    <nameField>
        <label>Claim settlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim settlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim_settlement__c/fields/Claim_Event__c.field-meta.xml
<CustomField>
    <fullName>Claim_Event__c</fullName>
    <label>Claim Event Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim_settlement__c/fields/Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>Exchange_Rate__c</fullName>
    <inlineHelpText>Based on USD</inlineHelpText>
    <label>Exchange Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim_settlement__c/fields/Local_Amount__c.field-meta.xml
<CustomField>
    <fullName>Local_Amount__c</fullName>
    <label>Local Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim_settlement__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/csettel.cls
@RestResource(urlMapping='/ClaimAPIII/*')
global class csettel {
    @HttpGet
    global static Claim_settlement__c claimSettelMtd(){
        RestRequest request = RestContext.request;
        
        String claimRec = request.requestURI.substring(
            request.requestURI.lastIndexOf('/')+1);
        
        Claim_settlement__c result = [Select Id,Name,Exchange_Rate__c,Local_Amount__c,Local_Currency__c,	Claim_Event__c from Claim_settlement__c Limit 1];
        return result;
    }
    
}