force-app/main/default/objects/Claim_settlement__c/Claim_settlement__c.object-meta.xml
<CustomObject>
    <label>Claim settlement</label>
    <nameField>
        <label>Claim settlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim settlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim_settlement__c/fields/Local_Amount__c.field-meta.xml
<CustomField>
    <fullName>Local_Amount__c</fullName>
    <label>Local Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim_settlement__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/claimSettel_Class.cls
@isTest
global class claimSettel_Class {
      @isTest
      static void getWebserviceTest() { 
        Claim_settlement__c csRec = new  Claim_settlement__c ();
        csRec.Name ='Test Name';
        csRec.Local_Currency__c='INR';
        csRec.Local_Amount__c=1000;
        insert csRec;
        
        RestContext.request = new RestRequest();
        RestContext.response = new RestResponse();
        RestContext.request.requestURI = '/services/apexRest/ClaimAPI/' + csRec.Id;
        RestContext.request.httpMethod = 'GET';
        claimSettel.claimSettelMtd();
      }
    
    
    @isTest
    static void postWebserviceTest() { 
        Test.startTest();
        String Name = 'Test';
        String Currenci = 'INR';
        Decimal Amt = 1.0;
        Decimal exchangeRate =1.0;
        Decimal convertedAmt = 1.1;
        
        Test.setMock(HttpCalloutMock.class,new HMC_HttpCalloutMockClass());
        claimSettel.recordInsert(Name,Currenci,Amt,exchangeRate,convertedAmt);
        Test.stopTest();
        
    }
}