force-app/main/default/objects/Claim_settlement__c/Claim_settlement__c.object-meta.xml
<CustomObject>
    <label>Claim settlement</label>
    <nameField>
        <label>Claim settlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Claim settlements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Claim_settlement__c/fields/Claim_Event__c.field-meta.xml
<CustomField>
    <fullName>Claim_Event__c</fullName>
    <label>Claim Event Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Claim_settlement__c/fields/Converted_Amount_USD__c.field-meta.xml
<CustomField>
    <fullName>Converted_Amount_USD__c</fullName>
    <label>Converted Amount (USD)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim_settlement__c/fields/Exchange_Rate__c.field-meta.xml
<CustomField>
    <fullName>Exchange_Rate__c</fullName>
    <inlineHelpText>Based on USD</inlineHelpText>
    <label>Exchange Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim_settlement__c/fields/Local_Amount__c.field-meta.xml
<CustomField>
    <fullName>Local_Amount__c</fullName>
    <label>Local Amount</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Claim_settlement__c/fields/Local_Currency__c.field-meta.xml
<CustomField>
    <fullName>Local_Currency__c</fullName>
    <label>Local Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/claimSettel.cls
@RestResource(urlMapping='/ClaimAPI/*')
global class claimSettel {
    @HttpGet
    global static Claim_settlement__c claimSettelMtd(){
        RestRequest request = RestContext.request;
        
        String claimRec = request.requestURI.substring(
            request.requestURI.lastIndexOf('/')+1);
        system.debug('Record'+claimRec);
        Claim_settlement__c result = [Select Id,Name,Exchange_Rate__c,Local_Amount__c,Local_Currency__c,Claim_Event__c from Claim_settlement__c where id =:claimRec Limit 1];
        return result;	
    }
    @HttpPost
    global static Claim_settlement__c recordInsert(String Name,String currencyType,Decimal amt,Decimal exchangeRate,Decimal convertedAmt) 
    {
        system.debug('Claim_settlement__c'+Name);
        system.debug('Claim_settlement__c'+currencyType);
        system.debug('Claim_settlement__c'+amt);
        system.debug('Claim_settlement__c'+exchangeRate);
        system.debug('Claim_settlement__c'+convertedAmt);
        
        
        string rate;
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndPoint('https://v6.exchangerate-api.com/v6/5cf8535b087045f4f75d57af/latest/USD');
        request.setMethod('GET');
        
        HttpResponse response = http.send(request);
        System.debug('response.getBody()'+response.getBody());
        
        Map<String,Object> results = (Map<String,Object>)JSON.deserializeUntyped(response.getBody());
        system.debug(results);
        Map<String,Object> dataMap = (Map<String, Object>) results.get('conversion_rates');
        system.debug(dataMap);
        
        for(String str: dataMap.keyset()) {
            system.debug('###'+str); 
            String Value = '' + dataMap.get(str);
            system.debug('###'+Value);
        }
        Claim_settlement__c claimObj = new Claim_settlement__c ();
        claimObj.Name = Name;
        claimObj.Local_Currency__c = currencyType;
        claimObj.Local_Amount__c = amt;
        Decimal exchange = Decimal.valueOf(dataMap.get(currencyType)+'');
        claimObj.Exchange_Rate__c = exchange;
        system.debug(claimObj.Exchange_Rate__c);
        claimObj.Converted_Amount_USD__c = amt/exchange;
        claimObj.Claim_Event__c = System.today();
        insert claimObj;
        
        if(response.getStatusCode() == 200) {
            system.debug(response.getStatusCode());
        }
        return claimObj;
    }
    
}