force-app/main/default/objects/Invoice_Object__c/Invoice_Object__c.object-meta.xml
<CustomObject>
    <label>Invoice Object</label>
    <nameField>
        <label>Invoice Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Object__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Invoice Objects</relationshipLabel>
    <relationshipName>Invoice_Objects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Object__c/fields/Invoice_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_End_Date__c</fullName>
    <label>Invoice End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Object__c/fields/Invoice_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Start_Date__c</fullName>
    <label>Invoice Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/invoiceCreate.cls
public class invoiceCreate {
    @AuraEnabled
    public static String createInvoiceRec (string invoiceRec){
        system.debug(invoiceRec);
        List <Invoice_Object__c> invoiceList = new List <Invoice_Object__c>();
        Invoice_Object__c invoiceLst = (Invoice_Object__c) System.JSON.deserialize(invoiceRec, Invoice_Object__c.class);
        system.debug('invoiceLst '+ invoiceLst);
        Invoice_Object__c InvoiceObj = new Invoice_Object__c();
        InvoiceObj.Invoice_Date__c = invoiceLst.Invoice_Date__c;
        system.debug('@@@@ '+InvoiceObj.Invoice_Date__c);
        InvoiceObj.Invoice_Start_Date__c = invoiceLst.Invoice_Start_Date__c;
        InvoiceObj.Invoice_End_Date__c = invoiceLst.Invoice_Start_Date__c.addDays(15);
        InvoiceObj.Contact__c = invoiceLst.Contact__c;
       // InvoiceObj.Name = 'ABC';
        system.debug('InvoiceObj '+InvoiceObj);
        Insert InvoiceObj;
        return InvoiceObj.Id;
    }
    
}