force-app/main/default/objects/student__c/student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/student__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/student__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <label>Fee Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Defaulter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StudentDefaulterCaseHelper.cls
public class StudentDefaulterCaseHelper {
    public static void BeforeInsertCaseMtd(List<Student__c> studentLst){
        
        List<Case> CaseOfStudent = new List <Case>();
        List<Student__c> studentList= new List <Student__c>();
        string text ='Defaulter student -';
        
        for(student__c stu : studentLst){
            if(stu.Fee__c!=null){
                if(stu.Fee__c=='Defaulter'){
                    case caseRec = new case();
                    caseRec.Status='New';
                    caseRec.origin='Phone';
                    caseRec.Subject=text+stu.Name;
                    CaseOfStudent.add(caseRec);
                } 
            }
        }
        if(!CaseOfStudent.isEmpty()){
            insert CaseOfStudent;
            For(Integer i=0 ;i<CaseOfStudent.Size();i++){
                for(student__c stu : studentLst){
                    stu.Case__c = CaseOfStudent[i].Id;
                } 
            }
        } 
    }
}